create table CATEGORY(
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR NOT NULL,
  REQ_NAME VARCHAR,
  DELETED BOOLEAN
);

create table BANNER(
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR NOT NULL,
  PRICE DECIMAL(10, 2),
  CATEGORY_ID BIGINT NOT NULL,
  CONTENT VARCHAR,
  DELETED BOOLEAN,
  FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID)
);

create table REQUEST(
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BANNER_ID BIGINT NOT NULL,
    USER_AGENT VARCHAR,
    IP_ADDRESS VARCHAR,
    REQ_DATE TIMESTAMP,
    FOREIGN KEY(BANNER_ID) REFERENCES BANNER(ID)
);

